name: Ember Films™
description: The award winning production company.
baseurl: https://www.website.com
google-analytics: GA-XXXX

telephone: "+44 (0) 8448 099 567"
email: "info@emberfilms.co.uk"
linkedin: "https://www.linkedin.com/company/ember-films"
twitter: "https://twitter.com/EmberFilms"
facebook: "https://www.facebook.com/EmberFilms"
instagram:  "https://www.instagram.com/ember_films/"
vimeo: "https://vimeo.com/emberfilms"

offices:
    - title: London
      phone: +44 (0) 8448 099 567
      email: info@emberfilms.co.uk
      address: 'Unit 7 & 8,<br/> Hackford Business Centre,<br/> Norfolk,<br/>  NR18 9HF'
      text-color: C65107
      bg-color: ffffff
    - title: Norwich
      phone: +44 (0) 8448 099 567
      email: info@emberfilms.co.uk
      address: 'Grantham Road,<br/> Chiswick,<br/> London,<br/> E12 5LX'
      text-color: ffffff
      bg-color: C65107


markdown: kramdown
permalink: /blog/:title/

collections:
    work:
        output: true
    services:
        output: true

# The release of Jekyll Now that you're using
version: v3.0.1

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

exclude:
    - .tmp
    - dev
    - dist
    - node_modules
    - gulpfile.js
    - package.json
    - bower.json
    - bower_components
    - gulpfile.babel.js
    - README.md
    - editorconfig
    - scripts
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - CNAME
