title: Jekyll, Gulp, Bower, Sass & Minification
description: Template generator for Jekyll etc.
baseurl: https://www.website.com
google-analytics: GA-XXXX

markdown: kramdown
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v3.0.1

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jemoji

exclude:
    - .tmp
    - dev
    - dist
    - node_modules
    - gulpfile.js
    - package.json
    - bower.json
    - bower_components
    - gulpfile.babel.js
    - README.md
    - editorconfig
    - scripts
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - CNAME
