name: Ember Films™
description: The award winning production company.
baseurl: https://www.website.com
google-analytics: GA-XXXX

telephone: "+44 (0) 8448 099 567"
email: "info@emberfilms.co.uk"
linkedin: "https://www.linkedin.com/company/ember-films"
twitter: "https://twitter.com/EmberFilms"
facebook: "https://www.facebook.com/EmberFilms"
instagram:  "https://www.instagram.com/ember_films/"
vimeo: "https://vimeo.com/emberfilms"


markdown: kramdown
permalink: /blog/:title/

collections:
    work:
        output: true
        permalink: :permalink/

# The release of Jekyll Now that you're using
version: v3.0.1

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

exclude:
    - .tmp
    - dev
    - dist
    - node_modules
    - gulpfile.js
    - package.json
    - bower.json
    - bower_components
    - gulpfile.babel.js
    - README.md
    - editorconfig
    - scripts
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - CNAME
